name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Set VITE_BASE for production
              if: github.ref == 'refs/heads/main'
              run: |
                  echo "VITE_BASE=/icsped/" >> $GITHUB_ENV

            - name: Build
              run: |
                  npm run build -- --base=$VITE_BASE

            - name: Deploy to gh-pages (main branch)
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
